name: Rollback to Previous Deployment

on:
  workflow_run:
    workflows: ["Deploy to ECS"]
    types:
      - completed

jobs:
  rollback:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        attempt: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait before rollback attempt ${{ matrix.attempt }}
        run: sleep $(( ${{ matrix.attempt }} * 300 ))
      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}


      - name: Check for CloudWatch Alarms
        id: check_alarm_state
        run: |
          CPU_ALARM_STATE=$(aws cloudwatch describe-alarms --alarm-names "HighCPUUtilization" --state-value ALARM --query 'MetricAlarms[0].StateValue' --region ***)
          MEMORY_ALARM_STATE=$(aws cloudwatch describe-alarms --alarm-names "HighMemoryUtilization" --state-value ALARM --query 'MetricAlarms[0].StateValue' --region ***)
          HTTP_ALARM_STATE=$(aws cloudwatch describe-alarms --alarm-names "HighHTTP5xxErrors" --state-value ALARM --query 'MetricAlarms[0].StateValue' --region ***)

          if [[ "$CPU_ALARM_STATE" == "ALARM" ]] || [[ "$MEMORY_ALARM_STATE" == "ALARM" ]] || [[ "$HTTP_ALARM_STATE" == "ALARM" ]]; then
            echo "ALARM"
            echo "::set-output name=alarm_state::ALARM"
          else
            echo "OK"
            echo "::set-output name=alarm_state::OK"
          fi


      - name: Get the second-to-last task definition revision
        id: get_previous_task_definition
        run: |
          if [ "${{ steps.check_alarm_state.outputs.alarm_state }}" == "ALARM" ]; then
            TASK_DEFINITION=$(aws ecs describe-services --cluster ${{ secrets.ECS_CLUSTER }} --services ${{ secrets.ECS_SERVICE }} --query 'services[0].deployments[1].taskDefinition' --output text)
            echo "::set-output name=task_definition::${TASK_DEFINITION}"
          else
            echo "No alarm, no rollback needed."
            exit 0
      
      - name: Rollback to previous task definition
        if: steps.check_alarm_state.outputs.alarm_state == 'ALARM'
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --task-definition ${{ steps.get_previous_task_definition.outputs.task_definition }}

      
